---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: crdvalidator-system/crd-validation-webhook-certificate
    release.openshift.io/feature-set: TechPreviewNoUpgrade
  name: crd-validation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: crd-validation-webhook
        namespace: openshift-crd-validator
        path: /validate-crd
        port: 9443
    name: webhook.crdvalidator.io
    objectSelector:
      matchLabels:
        core.rukpak.io/owner-kind: BundleDeployment
    rules:
      - apiGroups:
          - apiextensions.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - customresourcedefinitions
        scope: '*'
    sideEffects: None
